// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: pkg/grpc/service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GitServerManagement_CreateRepository_FullMethodName     = "/softserve.GitServerManagement/CreateRepository"
	GitServerManagement_DeleteRepository_FullMethodName     = "/softserve.GitServerManagement/DeleteRepository"
	GitServerManagement_GetRepository_FullMethodName        = "/softserve.GitServerManagement/GetRepository"
	GitServerManagement_ListRepositories_FullMethodName     = "/softserve.GitServerManagement/ListRepositories"
	GitServerManagement_RenameRepository_FullMethodName     = "/softserve.GitServerManagement/RenameRepository"
	GitServerManagement_UpdateRepository_FullMethodName     = "/softserve.GitServerManagement/UpdateRepository"
	GitServerManagement_ImportRepository_FullMethodName     = "/softserve.GitServerManagement/ImportRepository"
	GitServerManagement_GetTree_FullMethodName              = "/softserve.GitServerManagement/GetTree"
	GitServerManagement_GetBlob_FullMethodName              = "/softserve.GitServerManagement/GetBlob"
	GitServerManagement_GetBranches_FullMethodName          = "/softserve.GitServerManagement/GetBranches"
	GitServerManagement_ListCommits_FullMethodName          = "/softserve.GitServerManagement/ListCommits"
	GitServerManagement_GetCommit_FullMethodName            = "/softserve.GitServerManagement/GetCommit"
	GitServerManagement_ListUserRepositories_FullMethodName = "/softserve.GitServerManagement/ListUserRepositories"
	GitServerManagement_ListTags_FullMethodName             = "/softserve.GitServerManagement/ListTags"
	GitServerManagement_GetTag_FullMethodName               = "/softserve.GitServerManagement/GetTag"
	GitServerManagement_CreateTag_FullMethodName            = "/softserve.GitServerManagement/CreateTag"
	GitServerManagement_DeleteTag_FullMethodName            = "/softserve.GitServerManagement/DeleteTag"
	GitServerManagement_CompareBranches_FullMethodName      = "/softserve.GitServerManagement/CompareBranches"
	GitServerManagement_CompareCommits_FullMethodName       = "/softserve.GitServerManagement/CompareCommits"
	GitServerManagement_GetDefaultBranch_FullMethodName     = "/softserve.GitServerManagement/GetDefaultBranch"
	GitServerManagement_SetDefaultBranch_FullMethodName     = "/softserve.GitServerManagement/SetDefaultBranch"
	GitServerManagement_GetCloneURLs_FullMethodName         = "/softserve.GitServerManagement/GetCloneURLs"
	GitServerManagement_GetRepositoryStats_FullMethodName   = "/softserve.GitServerManagement/GetRepositoryStats"
	GitServerManagement_GetFileHistory_FullMethodName       = "/softserve.GitServerManagement/GetFileHistory"
	GitServerManagement_SearchCommits_FullMethodName        = "/softserve.GitServerManagement/SearchCommits"
	GitServerManagement_CheckPath_FullMethodName            = "/softserve.GitServerManagement/CheckPath"
	GitServerManagement_CreateUser_FullMethodName           = "/softserve.GitServerManagement/CreateUser"
	GitServerManagement_DeleteUser_FullMethodName           = "/softserve.GitServerManagement/DeleteUser"
	GitServerManagement_GetUser_FullMethodName              = "/softserve.GitServerManagement/GetUser"
	GitServerManagement_ListUsers_FullMethodName            = "/softserve.GitServerManagement/ListUsers"
	GitServerManagement_UpdateUser_FullMethodName           = "/softserve.GitServerManagement/UpdateUser"
	GitServerManagement_AddPublicKey_FullMethodName         = "/softserve.GitServerManagement/AddPublicKey"
	GitServerManagement_RemovePublicKey_FullMethodName      = "/softserve.GitServerManagement/RemovePublicKey"
	GitServerManagement_ListPublicKeys_FullMethodName       = "/softserve.GitServerManagement/ListPublicKeys"
	GitServerManagement_AddCollaborator_FullMethodName      = "/softserve.GitServerManagement/AddCollaborator"
	GitServerManagement_RemoveCollaborator_FullMethodName   = "/softserve.GitServerManagement/RemoveCollaborator"
	GitServerManagement_ListCollaborators_FullMethodName    = "/softserve.GitServerManagement/ListCollaborators"
	GitServerManagement_CreateAccessToken_FullMethodName    = "/softserve.GitServerManagement/CreateAccessToken"
	GitServerManagement_DeleteAccessToken_FullMethodName    = "/softserve.GitServerManagement/DeleteAccessToken"
	GitServerManagement_ListAccessTokens_FullMethodName     = "/softserve.GitServerManagement/ListAccessTokens"
	GitServerManagement_CreateWebhook_FullMethodName        = "/softserve.GitServerManagement/CreateWebhook"
	GitServerManagement_DeleteWebhook_FullMethodName        = "/softserve.GitServerManagement/DeleteWebhook"
	GitServerManagement_GetWebhook_FullMethodName           = "/softserve.GitServerManagement/GetWebhook"
	GitServerManagement_ListWebhooks_FullMethodName         = "/softserve.GitServerManagement/ListWebhooks"
	GitServerManagement_UpdateWebhook_FullMethodName        = "/softserve.GitServerManagement/UpdateWebhook"
	GitServerManagement_GetSettings_FullMethodName          = "/softserve.GitServerManagement/GetSettings"
	GitServerManagement_UpdateSettings_FullMethodName       = "/softserve.GitServerManagement/UpdateSettings"
	GitServerManagement_HealthCheck_FullMethodName          = "/softserve.GitServerManagement/HealthCheck"
)

// GitServerManagementClient is the client API for GitServerManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GitServerManagement provides full administrative control over the Soft Serve git server
type GitServerManagementClient interface {
	// Repository Management
	CreateRepository(ctx context.Context, in *CreateRepositoryRequest, opts ...grpc.CallOption) (*Repository, error)
	DeleteRepository(ctx context.Context, in *DeleteRepositoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetRepository(ctx context.Context, in *GetRepositoryRequest, opts ...grpc.CallOption) (*Repository, error)
	ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error)
	RenameRepository(ctx context.Context, in *RenameRepositoryRequest, opts ...grpc.CallOption) (*Repository, error)
	UpdateRepository(ctx context.Context, in *UpdateRepositoryRequest, opts ...grpc.CallOption) (*Repository, error)
	ImportRepository(ctx context.Context, in *ImportRepositoryRequest, opts ...grpc.CallOption) (*Repository, error)
	// Repository Content Browsing
	GetTree(ctx context.Context, in *GetTreeRequest, opts ...grpc.CallOption) (*GetTreeResponse, error)
	GetBlob(ctx context.Context, in *GetBlobRequest, opts ...grpc.CallOption) (*GetBlobResponse, error)
	GetBranches(ctx context.Context, in *GetBranchesRequest, opts ...grpc.CallOption) (*GetBranchesResponse, error)
	ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error)
	GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*CommitDetail, error)
	ListUserRepositories(ctx context.Context, in *ListUserRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error)
	// Tags
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	GetTag(ctx context.Context, in *GetTagRequest, opts ...grpc.CallOption) (*TagDetail, error)
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagDetail, error)
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Diff & Compare
	CompareBranches(ctx context.Context, in *CompareBranchesRequest, opts ...grpc.CallOption) (*CompareResponse, error)
	CompareCommits(ctx context.Context, in *CompareCommitsRequest, opts ...grpc.CallOption) (*CompareResponse, error)
	// Repository Info
	GetDefaultBranch(ctx context.Context, in *GetDefaultBranchRequest, opts ...grpc.CallOption) (*DefaultBranchResponse, error)
	SetDefaultBranch(ctx context.Context, in *SetDefaultBranchRequest, opts ...grpc.CallOption) (*DefaultBranchResponse, error)
	GetCloneURLs(ctx context.Context, in *GetCloneURLsRequest, opts ...grpc.CallOption) (*CloneURLsResponse, error)
	GetRepositoryStats(ctx context.Context, in *GetRepositoryStatsRequest, opts ...grpc.CallOption) (*RepositoryStatsResponse, error)
	// Advanced Operations
	GetFileHistory(ctx context.Context, in *GetFileHistoryRequest, opts ...grpc.CallOption) (*GetFileHistoryResponse, error)
	SearchCommits(ctx context.Context, in *SearchCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error)
	CheckPath(ctx context.Context, in *CheckPathRequest, opts ...grpc.CallOption) (*CheckPathResponse, error)
	// User Management
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
	// User Public Keys
	AddPublicKey(ctx context.Context, in *AddPublicKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemovePublicKey(ctx context.Context, in *RemovePublicKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListPublicKeys(ctx context.Context, in *ListPublicKeysRequest, opts ...grpc.CallOption) (*ListPublicKeysResponse, error)
	// Collaborator Management
	AddCollaborator(ctx context.Context, in *AddCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveCollaborator(ctx context.Context, in *RemoveCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListCollaborators(ctx context.Context, in *ListCollaboratorsRequest, opts ...grpc.CallOption) (*ListCollaboratorsResponse, error)
	// Access Token Management
	CreateAccessToken(ctx context.Context, in *CreateAccessTokenRequest, opts ...grpc.CallOption) (*AccessToken, error)
	DeleteAccessToken(ctx context.Context, in *DeleteAccessTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListAccessTokens(ctx context.Context, in *ListAccessTokensRequest, opts ...grpc.CallOption) (*ListAccessTokensResponse, error)
	// Webhook Management
	CreateWebhook(ctx context.Context, in *CreateWebhookRequest, opts ...grpc.CallOption) (*Webhook, error)
	DeleteWebhook(ctx context.Context, in *DeleteWebhookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetWebhook(ctx context.Context, in *GetWebhookRequest, opts ...grpc.CallOption) (*Webhook, error)
	ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*ListWebhooksResponse, error)
	UpdateWebhook(ctx context.Context, in *UpdateWebhookRequest, opts ...grpc.CallOption) (*Webhook, error)
	// Server Settings
	GetSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerSettings, error)
	UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*ServerSettings, error)
	// Health Check
	HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type gitServerManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewGitServerManagementClient(cc grpc.ClientConnInterface) GitServerManagementClient {
	return &gitServerManagementClient{cc}
}

func (c *gitServerManagementClient) CreateRepository(ctx context.Context, in *CreateRepositoryRequest, opts ...grpc.CallOption) (*Repository, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repository)
	err := c.cc.Invoke(ctx, GitServerManagement_CreateRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) DeleteRepository(ctx context.Context, in *DeleteRepositoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GitServerManagement_DeleteRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) GetRepository(ctx context.Context, in *GetRepositoryRequest, opts ...grpc.CallOption) (*Repository, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repository)
	err := c.cc.Invoke(ctx, GitServerManagement_GetRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) ListRepositories(ctx context.Context, in *ListRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepositoriesResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_ListRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) RenameRepository(ctx context.Context, in *RenameRepositoryRequest, opts ...grpc.CallOption) (*Repository, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repository)
	err := c.cc.Invoke(ctx, GitServerManagement_RenameRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) UpdateRepository(ctx context.Context, in *UpdateRepositoryRequest, opts ...grpc.CallOption) (*Repository, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repository)
	err := c.cc.Invoke(ctx, GitServerManagement_UpdateRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) ImportRepository(ctx context.Context, in *ImportRepositoryRequest, opts ...grpc.CallOption) (*Repository, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Repository)
	err := c.cc.Invoke(ctx, GitServerManagement_ImportRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) GetTree(ctx context.Context, in *GetTreeRequest, opts ...grpc.CallOption) (*GetTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTreeResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_GetTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) GetBlob(ctx context.Context, in *GetBlobRequest, opts ...grpc.CallOption) (*GetBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlobResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_GetBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) GetBranches(ctx context.Context, in *GetBranchesRequest, opts ...grpc.CallOption) (*GetBranchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBranchesResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_GetBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommitsResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_ListCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*CommitDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitDetail)
	err := c.cc.Invoke(ctx, GitServerManagement_GetCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) ListUserRepositories(ctx context.Context, in *ListUserRepositoriesRequest, opts ...grpc.CallOption) (*ListRepositoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRepositoriesResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_ListUserRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) GetTag(ctx context.Context, in *GetTagRequest, opts ...grpc.CallOption) (*TagDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagDetail)
	err := c.cc.Invoke(ctx, GitServerManagement_GetTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagDetail)
	err := c.cc.Invoke(ctx, GitServerManagement_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GitServerManagement_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) CompareBranches(ctx context.Context, in *CompareBranchesRequest, opts ...grpc.CallOption) (*CompareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_CompareBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) CompareCommits(ctx context.Context, in *CompareCommitsRequest, opts ...grpc.CallOption) (*CompareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_CompareCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) GetDefaultBranch(ctx context.Context, in *GetDefaultBranchRequest, opts ...grpc.CallOption) (*DefaultBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefaultBranchResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_GetDefaultBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) SetDefaultBranch(ctx context.Context, in *SetDefaultBranchRequest, opts ...grpc.CallOption) (*DefaultBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefaultBranchResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_SetDefaultBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) GetCloneURLs(ctx context.Context, in *GetCloneURLsRequest, opts ...grpc.CallOption) (*CloneURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneURLsResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_GetCloneURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) GetRepositoryStats(ctx context.Context, in *GetRepositoryStatsRequest, opts ...grpc.CallOption) (*RepositoryStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepositoryStatsResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_GetRepositoryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) GetFileHistory(ctx context.Context, in *GetFileHistoryRequest, opts ...grpc.CallOption) (*GetFileHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileHistoryResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_GetFileHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) SearchCommits(ctx context.Context, in *SearchCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommitsResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_SearchCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) CheckPath(ctx context.Context, in *CheckPathRequest, opts ...grpc.CallOption) (*CheckPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPathResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_CheckPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, GitServerManagement_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GitServerManagement_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, GitServerManagement_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, GitServerManagement_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) AddPublicKey(ctx context.Context, in *AddPublicKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GitServerManagement_AddPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) RemovePublicKey(ctx context.Context, in *RemovePublicKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GitServerManagement_RemovePublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) ListPublicKeys(ctx context.Context, in *ListPublicKeysRequest, opts ...grpc.CallOption) (*ListPublicKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublicKeysResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_ListPublicKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) AddCollaborator(ctx context.Context, in *AddCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GitServerManagement_AddCollaborator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) RemoveCollaborator(ctx context.Context, in *RemoveCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GitServerManagement_RemoveCollaborator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) ListCollaborators(ctx context.Context, in *ListCollaboratorsRequest, opts ...grpc.CallOption) (*ListCollaboratorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollaboratorsResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_ListCollaborators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) CreateAccessToken(ctx context.Context, in *CreateAccessTokenRequest, opts ...grpc.CallOption) (*AccessToken, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessToken)
	err := c.cc.Invoke(ctx, GitServerManagement_CreateAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) DeleteAccessToken(ctx context.Context, in *DeleteAccessTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GitServerManagement_DeleteAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) ListAccessTokens(ctx context.Context, in *ListAccessTokensRequest, opts ...grpc.CallOption) (*ListAccessTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccessTokensResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_ListAccessTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) CreateWebhook(ctx context.Context, in *CreateWebhookRequest, opts ...grpc.CallOption) (*Webhook, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Webhook)
	err := c.cc.Invoke(ctx, GitServerManagement_CreateWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) DeleteWebhook(ctx context.Context, in *DeleteWebhookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GitServerManagement_DeleteWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) GetWebhook(ctx context.Context, in *GetWebhookRequest, opts ...grpc.CallOption) (*Webhook, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Webhook)
	err := c.cc.Invoke(ctx, GitServerManagement_GetWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*ListWebhooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWebhooksResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_ListWebhooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) UpdateWebhook(ctx context.Context, in *UpdateWebhookRequest, opts ...grpc.CallOption) (*Webhook, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Webhook)
	err := c.cc.Invoke(ctx, GitServerManagement_UpdateWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) GetSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ServerSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerSettings)
	err := c.cc.Invoke(ctx, GitServerManagement_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*ServerSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerSettings)
	err := c.cc.Invoke(ctx, GitServerManagement_UpdateSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitServerManagementClient) HealthCheck(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, GitServerManagement_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitServerManagementServer is the server API for GitServerManagement service.
// All implementations must embed UnimplementedGitServerManagementServer
// for forward compatibility.
//
// GitServerManagement provides full administrative control over the Soft Serve git server
type GitServerManagementServer interface {
	// Repository Management
	CreateRepository(context.Context, *CreateRepositoryRequest) (*Repository, error)
	DeleteRepository(context.Context, *DeleteRepositoryRequest) (*emptypb.Empty, error)
	GetRepository(context.Context, *GetRepositoryRequest) (*Repository, error)
	ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error)
	RenameRepository(context.Context, *RenameRepositoryRequest) (*Repository, error)
	UpdateRepository(context.Context, *UpdateRepositoryRequest) (*Repository, error)
	ImportRepository(context.Context, *ImportRepositoryRequest) (*Repository, error)
	// Repository Content Browsing
	GetTree(context.Context, *GetTreeRequest) (*GetTreeResponse, error)
	GetBlob(context.Context, *GetBlobRequest) (*GetBlobResponse, error)
	GetBranches(context.Context, *GetBranchesRequest) (*GetBranchesResponse, error)
	ListCommits(context.Context, *ListCommitsRequest) (*ListCommitsResponse, error)
	GetCommit(context.Context, *GetCommitRequest) (*CommitDetail, error)
	ListUserRepositories(context.Context, *ListUserRepositoriesRequest) (*ListRepositoriesResponse, error)
	// Tags
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	GetTag(context.Context, *GetTagRequest) (*TagDetail, error)
	CreateTag(context.Context, *CreateTagRequest) (*TagDetail, error)
	DeleteTag(context.Context, *DeleteTagRequest) (*emptypb.Empty, error)
	// Diff & Compare
	CompareBranches(context.Context, *CompareBranchesRequest) (*CompareResponse, error)
	CompareCommits(context.Context, *CompareCommitsRequest) (*CompareResponse, error)
	// Repository Info
	GetDefaultBranch(context.Context, *GetDefaultBranchRequest) (*DefaultBranchResponse, error)
	SetDefaultBranch(context.Context, *SetDefaultBranchRequest) (*DefaultBranchResponse, error)
	GetCloneURLs(context.Context, *GetCloneURLsRequest) (*CloneURLsResponse, error)
	GetRepositoryStats(context.Context, *GetRepositoryStatsRequest) (*RepositoryStatsResponse, error)
	// Advanced Operations
	GetFileHistory(context.Context, *GetFileHistoryRequest) (*GetFileHistoryResponse, error)
	SearchCommits(context.Context, *SearchCommitsRequest) (*ListCommitsResponse, error)
	CheckPath(context.Context, *CheckPathRequest) (*CheckPathResponse, error)
	// User Management
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
	// User Public Keys
	AddPublicKey(context.Context, *AddPublicKeyRequest) (*emptypb.Empty, error)
	RemovePublicKey(context.Context, *RemovePublicKeyRequest) (*emptypb.Empty, error)
	ListPublicKeys(context.Context, *ListPublicKeysRequest) (*ListPublicKeysResponse, error)
	// Collaborator Management
	AddCollaborator(context.Context, *AddCollaboratorRequest) (*emptypb.Empty, error)
	RemoveCollaborator(context.Context, *RemoveCollaboratorRequest) (*emptypb.Empty, error)
	ListCollaborators(context.Context, *ListCollaboratorsRequest) (*ListCollaboratorsResponse, error)
	// Access Token Management
	CreateAccessToken(context.Context, *CreateAccessTokenRequest) (*AccessToken, error)
	DeleteAccessToken(context.Context, *DeleteAccessTokenRequest) (*emptypb.Empty, error)
	ListAccessTokens(context.Context, *ListAccessTokensRequest) (*ListAccessTokensResponse, error)
	// Webhook Management
	CreateWebhook(context.Context, *CreateWebhookRequest) (*Webhook, error)
	DeleteWebhook(context.Context, *DeleteWebhookRequest) (*emptypb.Empty, error)
	GetWebhook(context.Context, *GetWebhookRequest) (*Webhook, error)
	ListWebhooks(context.Context, *ListWebhooksRequest) (*ListWebhooksResponse, error)
	UpdateWebhook(context.Context, *UpdateWebhookRequest) (*Webhook, error)
	// Server Settings
	GetSettings(context.Context, *emptypb.Empty) (*ServerSettings, error)
	UpdateSettings(context.Context, *UpdateSettingsRequest) (*ServerSettings, error)
	// Health Check
	HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error)
	mustEmbedUnimplementedGitServerManagementServer()
}

// UnimplementedGitServerManagementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitServerManagementServer struct{}

func (UnimplementedGitServerManagementServer) CreateRepository(context.Context, *CreateRepositoryRequest) (*Repository, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRepository not implemented")
}
func (UnimplementedGitServerManagementServer) DeleteRepository(context.Context, *DeleteRepositoryRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRepository not implemented")
}
func (UnimplementedGitServerManagementServer) GetRepository(context.Context, *GetRepositoryRequest) (*Repository, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepository not implemented")
}
func (UnimplementedGitServerManagementServer) ListRepositories(context.Context, *ListRepositoriesRequest) (*ListRepositoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRepositories not implemented")
}
func (UnimplementedGitServerManagementServer) RenameRepository(context.Context, *RenameRepositoryRequest) (*Repository, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameRepository not implemented")
}
func (UnimplementedGitServerManagementServer) UpdateRepository(context.Context, *UpdateRepositoryRequest) (*Repository, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRepository not implemented")
}
func (UnimplementedGitServerManagementServer) ImportRepository(context.Context, *ImportRepositoryRequest) (*Repository, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportRepository not implemented")
}
func (UnimplementedGitServerManagementServer) GetTree(context.Context, *GetTreeRequest) (*GetTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTree not implemented")
}
func (UnimplementedGitServerManagementServer) GetBlob(context.Context, *GetBlobRequest) (*GetBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlob not implemented")
}
func (UnimplementedGitServerManagementServer) GetBranches(context.Context, *GetBranchesRequest) (*GetBranchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBranches not implemented")
}
func (UnimplementedGitServerManagementServer) ListCommits(context.Context, *ListCommitsRequest) (*ListCommitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCommits not implemented")
}
func (UnimplementedGitServerManagementServer) GetCommit(context.Context, *GetCommitRequest) (*CommitDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommit not implemented")
}
func (UnimplementedGitServerManagementServer) ListUserRepositories(context.Context, *ListUserRepositoriesRequest) (*ListRepositoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserRepositories not implemented")
}
func (UnimplementedGitServerManagementServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedGitServerManagementServer) GetTag(context.Context, *GetTagRequest) (*TagDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTag not implemented")
}
func (UnimplementedGitServerManagementServer) CreateTag(context.Context, *CreateTagRequest) (*TagDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedGitServerManagementServer) DeleteTag(context.Context, *DeleteTagRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedGitServerManagementServer) CompareBranches(context.Context, *CompareBranchesRequest) (*CompareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareBranches not implemented")
}
func (UnimplementedGitServerManagementServer) CompareCommits(context.Context, *CompareCommitsRequest) (*CompareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareCommits not implemented")
}
func (UnimplementedGitServerManagementServer) GetDefaultBranch(context.Context, *GetDefaultBranchRequest) (*DefaultBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefaultBranch not implemented")
}
func (UnimplementedGitServerManagementServer) SetDefaultBranch(context.Context, *SetDefaultBranchRequest) (*DefaultBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDefaultBranch not implemented")
}
func (UnimplementedGitServerManagementServer) GetCloneURLs(context.Context, *GetCloneURLsRequest) (*CloneURLsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCloneURLs not implemented")
}
func (UnimplementedGitServerManagementServer) GetRepositoryStats(context.Context, *GetRepositoryStatsRequest) (*RepositoryStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepositoryStats not implemented")
}
func (UnimplementedGitServerManagementServer) GetFileHistory(context.Context, *GetFileHistoryRequest) (*GetFileHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileHistory not implemented")
}
func (UnimplementedGitServerManagementServer) SearchCommits(context.Context, *SearchCommitsRequest) (*ListCommitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchCommits not implemented")
}
func (UnimplementedGitServerManagementServer) CheckPath(context.Context, *CheckPathRequest) (*CheckPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPath not implemented")
}
func (UnimplementedGitServerManagementServer) CreateUser(context.Context, *CreateUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedGitServerManagementServer) DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedGitServerManagementServer) GetUser(context.Context, *GetUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedGitServerManagementServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedGitServerManagementServer) UpdateUser(context.Context, *UpdateUserRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedGitServerManagementServer) AddPublicKey(context.Context, *AddPublicKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPublicKey not implemented")
}
func (UnimplementedGitServerManagementServer) RemovePublicKey(context.Context, *RemovePublicKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePublicKey not implemented")
}
func (UnimplementedGitServerManagementServer) ListPublicKeys(context.Context, *ListPublicKeysRequest) (*ListPublicKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPublicKeys not implemented")
}
func (UnimplementedGitServerManagementServer) AddCollaborator(context.Context, *AddCollaboratorRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCollaborator not implemented")
}
func (UnimplementedGitServerManagementServer) RemoveCollaborator(context.Context, *RemoveCollaboratorRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveCollaborator not implemented")
}
func (UnimplementedGitServerManagementServer) ListCollaborators(context.Context, *ListCollaboratorsRequest) (*ListCollaboratorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollaborators not implemented")
}
func (UnimplementedGitServerManagementServer) CreateAccessToken(context.Context, *CreateAccessTokenRequest) (*AccessToken, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccessToken not implemented")
}
func (UnimplementedGitServerManagementServer) DeleteAccessToken(context.Context, *DeleteAccessTokenRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAccessToken not implemented")
}
func (UnimplementedGitServerManagementServer) ListAccessTokens(context.Context, *ListAccessTokensRequest) (*ListAccessTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAccessTokens not implemented")
}
func (UnimplementedGitServerManagementServer) CreateWebhook(context.Context, *CreateWebhookRequest) (*Webhook, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWebhook not implemented")
}
func (UnimplementedGitServerManagementServer) DeleteWebhook(context.Context, *DeleteWebhookRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWebhook not implemented")
}
func (UnimplementedGitServerManagementServer) GetWebhook(context.Context, *GetWebhookRequest) (*Webhook, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWebhook not implemented")
}
func (UnimplementedGitServerManagementServer) ListWebhooks(context.Context, *ListWebhooksRequest) (*ListWebhooksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWebhooks not implemented")
}
func (UnimplementedGitServerManagementServer) UpdateWebhook(context.Context, *UpdateWebhookRequest) (*Webhook, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWebhook not implemented")
}
func (UnimplementedGitServerManagementServer) GetSettings(context.Context, *emptypb.Empty) (*ServerSettings, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedGitServerManagementServer) UpdateSettings(context.Context, *UpdateSettingsRequest) (*ServerSettings, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSettings not implemented")
}
func (UnimplementedGitServerManagementServer) HealthCheck(context.Context, *emptypb.Empty) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGitServerManagementServer) mustEmbedUnimplementedGitServerManagementServer() {}
func (UnimplementedGitServerManagementServer) testEmbeddedByValue()                             {}

// UnsafeGitServerManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitServerManagementServer will
// result in compilation errors.
type UnsafeGitServerManagementServer interface {
	mustEmbedUnimplementedGitServerManagementServer()
}

func RegisterGitServerManagementServer(s grpc.ServiceRegistrar, srv GitServerManagementServer) {
	// If the following call panics, it indicates UnimplementedGitServerManagementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GitServerManagement_ServiceDesc, srv)
}

func _GitServerManagement_CreateRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).CreateRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_CreateRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).CreateRepository(ctx, req.(*CreateRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_DeleteRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).DeleteRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_DeleteRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).DeleteRepository(ctx, req.(*DeleteRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_GetRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).GetRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_GetRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).GetRepository(ctx, req.(*GetRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_ListRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).ListRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_ListRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).ListRepositories(ctx, req.(*ListRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_RenameRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).RenameRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_RenameRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).RenameRepository(ctx, req.(*RenameRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_UpdateRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).UpdateRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_UpdateRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).UpdateRepository(ctx, req.(*UpdateRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_ImportRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).ImportRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_ImportRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).ImportRepository(ctx, req.(*ImportRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_GetTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).GetTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_GetTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).GetTree(ctx, req.(*GetTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_GetBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).GetBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_GetBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).GetBlob(ctx, req.(*GetBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_GetBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).GetBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_GetBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).GetBranches(ctx, req.(*GetBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_ListCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).ListCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_ListCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).ListCommits(ctx, req.(*ListCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_GetCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).GetCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_GetCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).GetCommit(ctx, req.(*GetCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_ListUserRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).ListUserRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_ListUserRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).ListUserRepositories(ctx, req.(*ListUserRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_GetTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).GetTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_GetTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).GetTag(ctx, req.(*GetTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_CompareBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).CompareBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_CompareBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).CompareBranches(ctx, req.(*CompareBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_CompareCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).CompareCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_CompareCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).CompareCommits(ctx, req.(*CompareCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_GetDefaultBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).GetDefaultBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_GetDefaultBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).GetDefaultBranch(ctx, req.(*GetDefaultBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_SetDefaultBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).SetDefaultBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_SetDefaultBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).SetDefaultBranch(ctx, req.(*SetDefaultBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_GetCloneURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCloneURLsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).GetCloneURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_GetCloneURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).GetCloneURLs(ctx, req.(*GetCloneURLsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_GetRepositoryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepositoryStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).GetRepositoryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_GetRepositoryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).GetRepositoryStats(ctx, req.(*GetRepositoryStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_GetFileHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).GetFileHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_GetFileHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).GetFileHistory(ctx, req.(*GetFileHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_SearchCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).SearchCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_SearchCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).SearchCommits(ctx, req.(*SearchCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_CheckPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).CheckPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_CheckPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).CheckPath(ctx, req.(*CheckPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_AddPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).AddPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_AddPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).AddPublicKey(ctx, req.(*AddPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_RemovePublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).RemovePublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_RemovePublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).RemovePublicKey(ctx, req.(*RemovePublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_ListPublicKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).ListPublicKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_ListPublicKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).ListPublicKeys(ctx, req.(*ListPublicKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_AddCollaborator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCollaboratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).AddCollaborator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_AddCollaborator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).AddCollaborator(ctx, req.(*AddCollaboratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_RemoveCollaborator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCollaboratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).RemoveCollaborator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_RemoveCollaborator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).RemoveCollaborator(ctx, req.(*RemoveCollaboratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_ListCollaborators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollaboratorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).ListCollaborators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_ListCollaborators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).ListCollaborators(ctx, req.(*ListCollaboratorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_CreateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).CreateAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_CreateAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).CreateAccessToken(ctx, req.(*CreateAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_DeleteAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).DeleteAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_DeleteAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).DeleteAccessToken(ctx, req.(*DeleteAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_ListAccessTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccessTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).ListAccessTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_ListAccessTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).ListAccessTokens(ctx, req.(*ListAccessTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_CreateWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).CreateWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_CreateWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).CreateWebhook(ctx, req.(*CreateWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_DeleteWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).DeleteWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_DeleteWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).DeleteWebhook(ctx, req.(*DeleteWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_GetWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).GetWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_GetWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).GetWebhook(ctx, req.(*GetWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_ListWebhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).ListWebhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_ListWebhooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).ListWebhooks(ctx, req.(*ListWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_UpdateWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).UpdateWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_UpdateWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).UpdateWebhook(ctx, req.(*UpdateWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).GetSettings(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_UpdateSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).UpdateSettings(ctx, req.(*UpdateSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitServerManagement_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitServerManagementServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitServerManagement_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitServerManagementServer).HealthCheck(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// GitServerManagement_ServiceDesc is the grpc.ServiceDesc for GitServerManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitServerManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "softserve.GitServerManagement",
	HandlerType: (*GitServerManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRepository",
			Handler:    _GitServerManagement_CreateRepository_Handler,
		},
		{
			MethodName: "DeleteRepository",
			Handler:    _GitServerManagement_DeleteRepository_Handler,
		},
		{
			MethodName: "GetRepository",
			Handler:    _GitServerManagement_GetRepository_Handler,
		},
		{
			MethodName: "ListRepositories",
			Handler:    _GitServerManagement_ListRepositories_Handler,
		},
		{
			MethodName: "RenameRepository",
			Handler:    _GitServerManagement_RenameRepository_Handler,
		},
		{
			MethodName: "UpdateRepository",
			Handler:    _GitServerManagement_UpdateRepository_Handler,
		},
		{
			MethodName: "ImportRepository",
			Handler:    _GitServerManagement_ImportRepository_Handler,
		},
		{
			MethodName: "GetTree",
			Handler:    _GitServerManagement_GetTree_Handler,
		},
		{
			MethodName: "GetBlob",
			Handler:    _GitServerManagement_GetBlob_Handler,
		},
		{
			MethodName: "GetBranches",
			Handler:    _GitServerManagement_GetBranches_Handler,
		},
		{
			MethodName: "ListCommits",
			Handler:    _GitServerManagement_ListCommits_Handler,
		},
		{
			MethodName: "GetCommit",
			Handler:    _GitServerManagement_GetCommit_Handler,
		},
		{
			MethodName: "ListUserRepositories",
			Handler:    _GitServerManagement_ListUserRepositories_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _GitServerManagement_ListTags_Handler,
		},
		{
			MethodName: "GetTag",
			Handler:    _GitServerManagement_GetTag_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _GitServerManagement_CreateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _GitServerManagement_DeleteTag_Handler,
		},
		{
			MethodName: "CompareBranches",
			Handler:    _GitServerManagement_CompareBranches_Handler,
		},
		{
			MethodName: "CompareCommits",
			Handler:    _GitServerManagement_CompareCommits_Handler,
		},
		{
			MethodName: "GetDefaultBranch",
			Handler:    _GitServerManagement_GetDefaultBranch_Handler,
		},
		{
			MethodName: "SetDefaultBranch",
			Handler:    _GitServerManagement_SetDefaultBranch_Handler,
		},
		{
			MethodName: "GetCloneURLs",
			Handler:    _GitServerManagement_GetCloneURLs_Handler,
		},
		{
			MethodName: "GetRepositoryStats",
			Handler:    _GitServerManagement_GetRepositoryStats_Handler,
		},
		{
			MethodName: "GetFileHistory",
			Handler:    _GitServerManagement_GetFileHistory_Handler,
		},
		{
			MethodName: "SearchCommits",
			Handler:    _GitServerManagement_SearchCommits_Handler,
		},
		{
			MethodName: "CheckPath",
			Handler:    _GitServerManagement_CheckPath_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _GitServerManagement_CreateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _GitServerManagement_DeleteUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _GitServerManagement_GetUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _GitServerManagement_ListUsers_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _GitServerManagement_UpdateUser_Handler,
		},
		{
			MethodName: "AddPublicKey",
			Handler:    _GitServerManagement_AddPublicKey_Handler,
		},
		{
			MethodName: "RemovePublicKey",
			Handler:    _GitServerManagement_RemovePublicKey_Handler,
		},
		{
			MethodName: "ListPublicKeys",
			Handler:    _GitServerManagement_ListPublicKeys_Handler,
		},
		{
			MethodName: "AddCollaborator",
			Handler:    _GitServerManagement_AddCollaborator_Handler,
		},
		{
			MethodName: "RemoveCollaborator",
			Handler:    _GitServerManagement_RemoveCollaborator_Handler,
		},
		{
			MethodName: "ListCollaborators",
			Handler:    _GitServerManagement_ListCollaborators_Handler,
		},
		{
			MethodName: "CreateAccessToken",
			Handler:    _GitServerManagement_CreateAccessToken_Handler,
		},
		{
			MethodName: "DeleteAccessToken",
			Handler:    _GitServerManagement_DeleteAccessToken_Handler,
		},
		{
			MethodName: "ListAccessTokens",
			Handler:    _GitServerManagement_ListAccessTokens_Handler,
		},
		{
			MethodName: "CreateWebhook",
			Handler:    _GitServerManagement_CreateWebhook_Handler,
		},
		{
			MethodName: "DeleteWebhook",
			Handler:    _GitServerManagement_DeleteWebhook_Handler,
		},
		{
			MethodName: "GetWebhook",
			Handler:    _GitServerManagement_GetWebhook_Handler,
		},
		{
			MethodName: "ListWebhooks",
			Handler:    _GitServerManagement_ListWebhooks_Handler,
		},
		{
			MethodName: "UpdateWebhook",
			Handler:    _GitServerManagement_UpdateWebhook_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _GitServerManagement_GetSettings_Handler,
		},
		{
			MethodName: "UpdateSettings",
			Handler:    _GitServerManagement_UpdateSettings_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GitServerManagement_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/service.proto",
}
